name: Request a feature
description: Suggest a feature you want to see in AbstractMenus!
labels: 'type: enhancement'
body:
  - type: markdown
    attributes:
      value: |
        If you have a feature suggestion for AbstractMenus, read the following tips:
        1.  Fill out the template.
              This will help us understand what you're requesting and why you want us
              to add it.
        2.  Keep it simple.
              Make sure it's easy to understand what you're requesting. A good way is
              to keep it to one request per GitHub issue, as we can then easily track
              feature requests.
        3.  Check whether it has already been asked or added.
              You can search the issue tracker to see if your feature has already been
              requested at https://github.com/AbstractMenus/minecraft-plugin/issues. You can
              also check the changelogs to see if the feature was recently added:
              https://github.com/AbstractMenus/minecraft-plugin/releases
  - type: textarea
    attributes:
      label: Feature description
      description: Explain what you should expect to happen.
      placeholder: |
        What feature are you suggesting?
    validations:
      required: true
  - type: textarea
    attributes:
      label: How the feature is useful
      description: Explain what actually happens.
      placeholder: |
        How is the feature useful to players, server owners and/or developers?
    validations:
      required: true